version: '3.8'

services:
    web:
        build: .
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=production
            - SPRING_DATASOURCE_URL=${DB_URL} #Chưa sửa DB_URL
        depends_on:
            - db
    db: 
        image: "mysql:8.0"
        container_name: mysql_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./main.sql:/docker-entrypoint-initdb.d/main.sql

volumes:
    mysql_data: