INSERT INTO monhoc(mamh, tenmh, sotinchi, makhoa) VALUES
('IT001', 'Nhap mon lap trinh', 4, 'CS'),
('IT002', 'Lap trinh huong doi tuong', 4, 'SE'),
('IT003', 'Cau truc du lieu va giai thuat', 4, 'CS'),
('IT004', 'Co so du lieu', 4, 'IS'),
('IT005', 'Nhap mon mang may tinh', 4, 'MTTT'),
('IT006', 'Kien truc may tính', 3, 'CE'),
('IT007', 'He dieu hanh', 4, 'CE'),
('IT010', 'To chu va cau truc may tinh', 2, 'CE'),
('IT012', 'To chu va cau truc may tinh II', 4, 'CE'),
('IE101', 'Co so ha tang cong nghe thong tin', 3, 'ISE'),
('IE103', 'Quan ly thong tin', 4, 'ISE'),
('IE104', 'Internet va cong nghe Web', 4, 'ISE'),
('IE105', 'Nhap mon bao dam va an ninh thong tin', 4, 'ISE'),
('IE106', 'Thiet ke giao dien nguoi dung', 4, 'ISE'),
('IE108', 'Phan tich thiet ke phan mem', 4, 'ISE'),
('IS402', 'Dien toan dam may', 4, 'ISE'),
('IE102', 'Cac cong nghe nen', 2, 'ISE'),
('IE212', 'Cong nghe Du lieu lon', 3, 'ISE'),
('IE303', 'Cong nghe Java', 3, 'ISE'),
('IE207', 'Do an', 3, 'ISE'),
('DS204', 'Do an khoa hoc du lieu va ung dung', 3, 'ISE'),
('IE402', 'He thong thong tin dia ly 3 chieu', 3, 'ISE'),
('DS102', 'Hoc may thong ke', 3, 'ISE'),
('IE403', 'Khai thac du lieu truyen thong xa hoi', 3, 'ISE'),
('DS505', 'Khoa luan tot nghiep', 10, 'ISE'),
('IE213', 'Ky thuat phat trien he thong Web', 3, 'ISE'),
('DS200', 'Phan tich du lieu lon', 3, 'ISE'),
('DS304', 'Thiet ke va phan tich thuc nghiem', 3, 'ISE'),
('DS309', 'Thuc tap doanh nghiep', 2, 'ISE'),
('IE204', 'Toi uu hoa cong cu tim kiem', 3, 'ISE'),
('DS107', 'Tu duy tinh toan cho Khoa hoc du lieu', 3, 'ISE'),
('DS312', 'Xu ly anh y khoa', 3, 'ISE'),
('DS313', 'Xu ly thong tin giong noi', 3, 'ISE'),
('EC335', 'An toan va bao mat thuong mai dien tu', 3, 'IS'),
('IS211', 'Co so du lieu phan tan', 3, 'IS'),
('IS405', 'Du lieu lon', 3, 'IS'),
('IS210', 'He quan tri co so du lieu', 3, 'IS'),
('IS349', 'He thong y te', 3, 'IS'),
('IS336', 'Hoach dinh nguon luc doanh nghiep', 3, 'IS'),
('EC001', 'Kinh te hoc dai cuong', 4, 'IS'),
('IS216', 'Lap trinh Java', 3, 'IS'),
('IS353', 'Mang xa hoi', 3, 'IS'),
('EC101', 'Marketing can ban', 3, 'IS'),
('EC204', 'Marketing dien tu', 3, 'IS'),
('EC214', 'Nhap mon Quan tri chuoi cung ung', 3, 'IS'),
('IS403', 'Phan tich du lieu kinh doanh', 3, 'IS'),
('IS201', 'Phan tich thiet ke he thong thong tin', 3, 'IS'),
('EC201', 'Phan tich thiet ke quy trinh nghiep vu doanh nghiep', 3, 'IS'),
('EC229', 'Phap luat trong thuong mai dien tu', 3, 'IS'),
('EC402', 'Phat trien ung dung thuong mai di dong', 3, 'IS'),
('IS207', 'Phat trien ung dung web', 3, 'IS'),
('IS208', 'Quan ly du an cong nghe thong tin', 3, 'IS'),
('EC208', 'Quan ly du an TMDT', 3, 'IS'),
('EC312', 'Thiet ke he thong thuong mai dien tu', 3, 'IS'),
('EC403', 'Thuong mai xa hoi', 3, 'IS');